name: contoso-traders-cloud-testing

on:
  workflow_dispatch:
  push:
    branches: ["main"]
    paths-ignore: ["docs/**"]
  pull_request:
    branches: ["main"]

jobs:
  deploy:
    strategy:
      matrix:
        environmentName: [staging, production]
    uses: ./.github/workflows/contoso-traders-provisioning-deployment-template.yml
    secrets: inherit
    with:
      environmentName: ${{ matrix.environmentName }}
