name: contoso-traders-cloud-testing

on:
  workflow_dispatch:
  push:
    branches: ["main"]
    paths-ignore: ["docs/**"]
  pull_request:
    branches: ["main"]

jobs:
  staging:
    uses: ./.github/workflows/contoso-traders-cloud-testing-template.yml
    secrets: inherit
    with:
      environmentName: staging
      configureAzureAD: ${{ vars.ENABLE_LOGIN == 'true' }}

  production:
    needs: staging
    uses: ./.github/workflows/contoso-traders-cloud-testing-template.yml
    secrets: inherit
    with:
      environmentName: production
      configureAzureAD: ${{ vars.ENABLE_LOGIN == 'true' }}
